// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/maximum/industries/instance.proto

package maximum.industries;

public final class Instance {
  private Instance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code maximum.industries.Player}
   */
  public enum Player
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WHITE = 0;</code>
     */
    WHITE(0),
    /**
     * <code>BLACK = 1;</code>
     */
    BLACK(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>WHITE = 0;</code>
     */
    public static final int WHITE_VALUE = 0;
    /**
     * <code>BLACK = 1;</code>
     */
    public static final int BLACK_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Player valueOf(int value) {
      return forNumber(value);
    }

    public static Player forNumber(int value) {
      switch (value) {
        case 0: return WHITE;
        case 1: return BLACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Player>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Player> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Player>() {
            public Player findValueByNumber(int number) {
              return Player.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return maximum.industries.Instance.getDescriptor().getEnumTypes().get(0);
    }

    private static final Player[] VALUES = values();

    public static Player valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Player(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:maximum.industries.Player)
  }

  /**
   * Protobuf enum {@code maximum.industries.TsrType}
   */
  public enum TsrType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MOVE_PROB = 0;</code>
     */
    MOVE_PROB(0),
    /**
     * <code>OUTCOME_PROB = 1;</code>
     */
    OUTCOME_PROB(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MOVE_PROB = 0;</code>
     */
    public static final int MOVE_PROB_VALUE = 0;
    /**
     * <code>OUTCOME_PROB = 1;</code>
     */
    public static final int OUTCOME_PROB_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TsrType valueOf(int value) {
      return forNumber(value);
    }

    public static TsrType forNumber(int value) {
      switch (value) {
        case 0: return MOVE_PROB;
        case 1: return OUTCOME_PROB;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TsrType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TsrType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TsrType>() {
            public TsrType findValueByNumber(int number) {
              return TsrType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return maximum.industries.Instance.getDescriptor().getEnumTypes().get(1);
    }

    private static final TsrType[] VALUES = values();

    public static TsrType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TsrType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:maximum.industries.TsrType)
  }

  public interface WinLoseDrawOrBuilder extends
      // @@protoc_insertion_point(interface_extends:maximum.industries.WinLoseDraw)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float win = 1;</code>
     */
    float getWin();

    /**
     * <code>float lose = 2;</code>
     */
    float getLose();

    /**
     * <code>float draw = 3;</code>
     */
    float getDraw();
  }
  /**
   * Protobuf type {@code maximum.industries.WinLoseDraw}
   */
  public  static final class WinLoseDraw extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:maximum.industries.WinLoseDraw)
      WinLoseDrawOrBuilder {
    // Use WinLoseDraw.newBuilder() to construct.
    private WinLoseDraw(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WinLoseDraw() {
      win_ = 0F;
      lose_ = 0F;
      draw_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WinLoseDraw(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              win_ = input.readFloat();
              break;
            }
            case 21: {

              lose_ = input.readFloat();
              break;
            }
            case 29: {

              draw_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return maximum.industries.Instance.internal_static_maximum_industries_WinLoseDraw_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return maximum.industries.Instance.internal_static_maximum_industries_WinLoseDraw_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              maximum.industries.Instance.WinLoseDraw.class, maximum.industries.Instance.WinLoseDraw.Builder.class);
    }

    public static final int WIN_FIELD_NUMBER = 1;
    private float win_;
    /**
     * <code>float win = 1;</code>
     */
    public float getWin() {
      return win_;
    }

    public static final int LOSE_FIELD_NUMBER = 2;
    private float lose_;
    /**
     * <code>float lose = 2;</code>
     */
    public float getLose() {
      return lose_;
    }

    public static final int DRAW_FIELD_NUMBER = 3;
    private float draw_;
    /**
     * <code>float draw = 3;</code>
     */
    public float getDraw() {
      return draw_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (win_ != 0F) {
        output.writeFloat(1, win_);
      }
      if (lose_ != 0F) {
        output.writeFloat(2, lose_);
      }
      if (draw_ != 0F) {
        output.writeFloat(3, draw_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (win_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, win_);
      }
      if (lose_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, lose_);
      }
      if (draw_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, draw_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof maximum.industries.Instance.WinLoseDraw)) {
        return super.equals(obj);
      }
      maximum.industries.Instance.WinLoseDraw other = (maximum.industries.Instance.WinLoseDraw) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getWin())
          == java.lang.Float.floatToIntBits(
              other.getWin()));
      result = result && (
          java.lang.Float.floatToIntBits(getLose())
          == java.lang.Float.floatToIntBits(
              other.getLose()));
      result = result && (
          java.lang.Float.floatToIntBits(getDraw())
          == java.lang.Float.floatToIntBits(
              other.getDraw()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WIN_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getWin());
      hash = (37 * hash) + LOSE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLose());
      hash = (37 * hash) + DRAW_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getDraw());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static maximum.industries.Instance.WinLoseDraw parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maximum.industries.Instance.WinLoseDraw parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maximum.industries.Instance.WinLoseDraw parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maximum.industries.Instance.WinLoseDraw parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maximum.industries.Instance.WinLoseDraw parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maximum.industries.Instance.WinLoseDraw parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maximum.industries.Instance.WinLoseDraw parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static maximum.industries.Instance.WinLoseDraw parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static maximum.industries.Instance.WinLoseDraw parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static maximum.industries.Instance.WinLoseDraw parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static maximum.industries.Instance.WinLoseDraw parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static maximum.industries.Instance.WinLoseDraw parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(maximum.industries.Instance.WinLoseDraw prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code maximum.industries.WinLoseDraw}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:maximum.industries.WinLoseDraw)
        maximum.industries.Instance.WinLoseDrawOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return maximum.industries.Instance.internal_static_maximum_industries_WinLoseDraw_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return maximum.industries.Instance.internal_static_maximum_industries_WinLoseDraw_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                maximum.industries.Instance.WinLoseDraw.class, maximum.industries.Instance.WinLoseDraw.Builder.class);
      }

      // Construct using maximum.industries.Instance.WinLoseDraw.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        win_ = 0F;

        lose_ = 0F;

        draw_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return maximum.industries.Instance.internal_static_maximum_industries_WinLoseDraw_descriptor;
      }

      public maximum.industries.Instance.WinLoseDraw getDefaultInstanceForType() {
        return maximum.industries.Instance.WinLoseDraw.getDefaultInstance();
      }

      public maximum.industries.Instance.WinLoseDraw build() {
        maximum.industries.Instance.WinLoseDraw result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public maximum.industries.Instance.WinLoseDraw buildPartial() {
        maximum.industries.Instance.WinLoseDraw result = new maximum.industries.Instance.WinLoseDraw(this);
        result.win_ = win_;
        result.lose_ = lose_;
        result.draw_ = draw_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof maximum.industries.Instance.WinLoseDraw) {
          return mergeFrom((maximum.industries.Instance.WinLoseDraw)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(maximum.industries.Instance.WinLoseDraw other) {
        if (other == maximum.industries.Instance.WinLoseDraw.getDefaultInstance()) return this;
        if (other.getWin() != 0F) {
          setWin(other.getWin());
        }
        if (other.getLose() != 0F) {
          setLose(other.getLose());
        }
        if (other.getDraw() != 0F) {
          setDraw(other.getDraw());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        maximum.industries.Instance.WinLoseDraw parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (maximum.industries.Instance.WinLoseDraw) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float win_ ;
      /**
       * <code>float win = 1;</code>
       */
      public float getWin() {
        return win_;
      }
      /**
       * <code>float win = 1;</code>
       */
      public Builder setWin(float value) {
        
        win_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float win = 1;</code>
       */
      public Builder clearWin() {
        
        win_ = 0F;
        onChanged();
        return this;
      }

      private float lose_ ;
      /**
       * <code>float lose = 2;</code>
       */
      public float getLose() {
        return lose_;
      }
      /**
       * <code>float lose = 2;</code>
       */
      public Builder setLose(float value) {
        
        lose_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float lose = 2;</code>
       */
      public Builder clearLose() {
        
        lose_ = 0F;
        onChanged();
        return this;
      }

      private float draw_ ;
      /**
       * <code>float draw = 3;</code>
       */
      public float getDraw() {
        return draw_;
      }
      /**
       * <code>float draw = 3;</code>
       */
      public Builder setDraw(float value) {
        
        draw_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float draw = 3;</code>
       */
      public Builder clearDraw() {
        
        draw_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:maximum.industries.WinLoseDraw)
    }

    // @@protoc_insertion_point(class_scope:maximum.industries.WinLoseDraw)
    private static final maximum.industries.Instance.WinLoseDraw DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new maximum.industries.Instance.WinLoseDraw();
    }

    public static maximum.industries.Instance.WinLoseDraw getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WinLoseDraw>
        PARSER = new com.google.protobuf.AbstractParser<WinLoseDraw>() {
      public WinLoseDraw parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WinLoseDraw(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WinLoseDraw> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WinLoseDraw> getParserForType() {
      return PARSER;
    }

    public maximum.industries.Instance.WinLoseDraw getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TreeSearchResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:maximum.industries.TreeSearchResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 index = 1;</code>
     */
    int getIndex();

    /**
     * <code>.maximum.industries.TsrType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>.maximum.industries.TsrType type = 2;</code>
     */
    maximum.industries.Instance.TsrType getType();

    /**
     * <code>float prob = 3;</code>
     */
    float getProb();

    /**
     * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
     */
    boolean hasWld();
    /**
     * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
     */
    maximum.industries.Instance.WinLoseDraw getWld();
    /**
     * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
     */
    maximum.industries.Instance.WinLoseDrawOrBuilder getWldOrBuilder();
  }
  /**
   * Protobuf type {@code maximum.industries.TreeSearchResult}
   */
  public  static final class TreeSearchResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:maximum.industries.TreeSearchResult)
      TreeSearchResultOrBuilder {
    // Use TreeSearchResult.newBuilder() to construct.
    private TreeSearchResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TreeSearchResult() {
      index_ = 0;
      type_ = 0;
      prob_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TreeSearchResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              index_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 29: {

              prob_ = input.readFloat();
              break;
            }
            case 34: {
              maximum.industries.Instance.WinLoseDraw.Builder subBuilder = null;
              if (wld_ != null) {
                subBuilder = wld_.toBuilder();
              }
              wld_ = input.readMessage(maximum.industries.Instance.WinLoseDraw.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(wld_);
                wld_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return maximum.industries.Instance.internal_static_maximum_industries_TreeSearchResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return maximum.industries.Instance.internal_static_maximum_industries_TreeSearchResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              maximum.industries.Instance.TreeSearchResult.class, maximum.industries.Instance.TreeSearchResult.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>uint32 index = 1;</code>
     */
    public int getIndex() {
      return index_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.maximum.industries.TsrType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.maximum.industries.TsrType type = 2;</code>
     */
    public maximum.industries.Instance.TsrType getType() {
      maximum.industries.Instance.TsrType result = maximum.industries.Instance.TsrType.valueOf(type_);
      return result == null ? maximum.industries.Instance.TsrType.UNRECOGNIZED : result;
    }

    public static final int PROB_FIELD_NUMBER = 3;
    private float prob_;
    /**
     * <code>float prob = 3;</code>
     */
    public float getProb() {
      return prob_;
    }

    public static final int WLD_FIELD_NUMBER = 4;
    private maximum.industries.Instance.WinLoseDraw wld_;
    /**
     * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
     */
    public boolean hasWld() {
      return wld_ != null;
    }
    /**
     * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
     */
    public maximum.industries.Instance.WinLoseDraw getWld() {
      return wld_ == null ? maximum.industries.Instance.WinLoseDraw.getDefaultInstance() : wld_;
    }
    /**
     * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
     */
    public maximum.industries.Instance.WinLoseDrawOrBuilder getWldOrBuilder() {
      return getWld();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeUInt32(1, index_);
      }
      if (type_ != maximum.industries.Instance.TsrType.MOVE_PROB.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (prob_ != 0F) {
        output.writeFloat(3, prob_);
      }
      if (wld_ != null) {
        output.writeMessage(4, getWld());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, index_);
      }
      if (type_ != maximum.industries.Instance.TsrType.MOVE_PROB.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (prob_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, prob_);
      }
      if (wld_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getWld());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof maximum.industries.Instance.TreeSearchResult)) {
        return super.equals(obj);
      }
      maximum.industries.Instance.TreeSearchResult other = (maximum.industries.Instance.TreeSearchResult) obj;

      boolean result = true;
      result = result && (getIndex()
          == other.getIndex());
      result = result && type_ == other.type_;
      result = result && (
          java.lang.Float.floatToIntBits(getProb())
          == java.lang.Float.floatToIntBits(
              other.getProb()));
      result = result && (hasWld() == other.hasWld());
      if (hasWld()) {
        result = result && getWld()
            .equals(other.getWld());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + PROB_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getProb());
      if (hasWld()) {
        hash = (37 * hash) + WLD_FIELD_NUMBER;
        hash = (53 * hash) + getWld().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static maximum.industries.Instance.TreeSearchResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maximum.industries.Instance.TreeSearchResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maximum.industries.Instance.TreeSearchResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maximum.industries.Instance.TreeSearchResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maximum.industries.Instance.TreeSearchResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maximum.industries.Instance.TreeSearchResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maximum.industries.Instance.TreeSearchResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static maximum.industries.Instance.TreeSearchResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static maximum.industries.Instance.TreeSearchResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static maximum.industries.Instance.TreeSearchResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static maximum.industries.Instance.TreeSearchResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static maximum.industries.Instance.TreeSearchResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(maximum.industries.Instance.TreeSearchResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code maximum.industries.TreeSearchResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:maximum.industries.TreeSearchResult)
        maximum.industries.Instance.TreeSearchResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return maximum.industries.Instance.internal_static_maximum_industries_TreeSearchResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return maximum.industries.Instance.internal_static_maximum_industries_TreeSearchResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                maximum.industries.Instance.TreeSearchResult.class, maximum.industries.Instance.TreeSearchResult.Builder.class);
      }

      // Construct using maximum.industries.Instance.TreeSearchResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        index_ = 0;

        type_ = 0;

        prob_ = 0F;

        if (wldBuilder_ == null) {
          wld_ = null;
        } else {
          wld_ = null;
          wldBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return maximum.industries.Instance.internal_static_maximum_industries_TreeSearchResult_descriptor;
      }

      public maximum.industries.Instance.TreeSearchResult getDefaultInstanceForType() {
        return maximum.industries.Instance.TreeSearchResult.getDefaultInstance();
      }

      public maximum.industries.Instance.TreeSearchResult build() {
        maximum.industries.Instance.TreeSearchResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public maximum.industries.Instance.TreeSearchResult buildPartial() {
        maximum.industries.Instance.TreeSearchResult result = new maximum.industries.Instance.TreeSearchResult(this);
        result.index_ = index_;
        result.type_ = type_;
        result.prob_ = prob_;
        if (wldBuilder_ == null) {
          result.wld_ = wld_;
        } else {
          result.wld_ = wldBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof maximum.industries.Instance.TreeSearchResult) {
          return mergeFrom((maximum.industries.Instance.TreeSearchResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(maximum.industries.Instance.TreeSearchResult other) {
        if (other == maximum.industries.Instance.TreeSearchResult.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getProb() != 0F) {
          setProb(other.getProb());
        }
        if (other.hasWld()) {
          mergeWld(other.getWld());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        maximum.industries.Instance.TreeSearchResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (maximum.industries.Instance.TreeSearchResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int index_ ;
      /**
       * <code>uint32 index = 1;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>uint32 index = 1;</code>
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 index = 1;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.maximum.industries.TsrType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.maximum.industries.TsrType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.maximum.industries.TsrType type = 2;</code>
       */
      public maximum.industries.Instance.TsrType getType() {
        maximum.industries.Instance.TsrType result = maximum.industries.Instance.TsrType.valueOf(type_);
        return result == null ? maximum.industries.Instance.TsrType.UNRECOGNIZED : result;
      }
      /**
       * <code>.maximum.industries.TsrType type = 2;</code>
       */
      public Builder setType(maximum.industries.Instance.TsrType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.maximum.industries.TsrType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private float prob_ ;
      /**
       * <code>float prob = 3;</code>
       */
      public float getProb() {
        return prob_;
      }
      /**
       * <code>float prob = 3;</code>
       */
      public Builder setProb(float value) {
        
        prob_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float prob = 3;</code>
       */
      public Builder clearProb() {
        
        prob_ = 0F;
        onChanged();
        return this;
      }

      private maximum.industries.Instance.WinLoseDraw wld_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          maximum.industries.Instance.WinLoseDraw, maximum.industries.Instance.WinLoseDraw.Builder, maximum.industries.Instance.WinLoseDrawOrBuilder> wldBuilder_;
      /**
       * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
       */
      public boolean hasWld() {
        return wldBuilder_ != null || wld_ != null;
      }
      /**
       * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
       */
      public maximum.industries.Instance.WinLoseDraw getWld() {
        if (wldBuilder_ == null) {
          return wld_ == null ? maximum.industries.Instance.WinLoseDraw.getDefaultInstance() : wld_;
        } else {
          return wldBuilder_.getMessage();
        }
      }
      /**
       * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
       */
      public Builder setWld(maximum.industries.Instance.WinLoseDraw value) {
        if (wldBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          wld_ = value;
          onChanged();
        } else {
          wldBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
       */
      public Builder setWld(
          maximum.industries.Instance.WinLoseDraw.Builder builderForValue) {
        if (wldBuilder_ == null) {
          wld_ = builderForValue.build();
          onChanged();
        } else {
          wldBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
       */
      public Builder mergeWld(maximum.industries.Instance.WinLoseDraw value) {
        if (wldBuilder_ == null) {
          if (wld_ != null) {
            wld_ =
              maximum.industries.Instance.WinLoseDraw.newBuilder(wld_).mergeFrom(value).buildPartial();
          } else {
            wld_ = value;
          }
          onChanged();
        } else {
          wldBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
       */
      public Builder clearWld() {
        if (wldBuilder_ == null) {
          wld_ = null;
          onChanged();
        } else {
          wld_ = null;
          wldBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
       */
      public maximum.industries.Instance.WinLoseDraw.Builder getWldBuilder() {
        
        onChanged();
        return getWldFieldBuilder().getBuilder();
      }
      /**
       * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
       */
      public maximum.industries.Instance.WinLoseDrawOrBuilder getWldOrBuilder() {
        if (wldBuilder_ != null) {
          return wldBuilder_.getMessageOrBuilder();
        } else {
          return wld_ == null ?
              maximum.industries.Instance.WinLoseDraw.getDefaultInstance() : wld_;
        }
      }
      /**
       * <code>.maximum.industries.WinLoseDraw wld = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          maximum.industries.Instance.WinLoseDraw, maximum.industries.Instance.WinLoseDraw.Builder, maximum.industries.Instance.WinLoseDrawOrBuilder> 
          getWldFieldBuilder() {
        if (wldBuilder_ == null) {
          wldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              maximum.industries.Instance.WinLoseDraw, maximum.industries.Instance.WinLoseDraw.Builder, maximum.industries.Instance.WinLoseDrawOrBuilder>(
                  getWld(),
                  getParentForChildren(),
                  isClean());
          wld_ = null;
        }
        return wldBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:maximum.industries.TreeSearchResult)
    }

    // @@protoc_insertion_point(class_scope:maximum.industries.TreeSearchResult)
    private static final maximum.industries.Instance.TreeSearchResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new maximum.industries.Instance.TreeSearchResult();
    }

    public static maximum.industries.Instance.TreeSearchResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TreeSearchResult>
        PARSER = new com.google.protobuf.AbstractParser<TreeSearchResult>() {
      public TreeSearchResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TreeSearchResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TreeSearchResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TreeSearchResult> getParserForType() {
      return PARSER;
    }

    public maximum.industries.Instance.TreeSearchResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TrainingInstanceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:maximum.industries.TrainingInstance)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes board_state = 1;</code>
     */
    com.google.protobuf.ByteString getBoardState();

    /**
     * <code>.maximum.industries.Player player = 2;</code>
     */
    int getPlayerValue();
    /**
     * <code>.maximum.industries.Player player = 2;</code>
     */
    maximum.industries.Instance.Player getPlayer();

    /**
     * <code>uint32 outcome = 3;</code>
     */
    int getOutcome();

    /**
     * <code>uint32 game_length = 4;</code>
     */
    int getGameLength();

    /**
     * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
     */
    java.util.List<maximum.industries.Instance.TreeSearchResult> 
        getTreeSearchResultList();
    /**
     * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
     */
    maximum.industries.Instance.TreeSearchResult getTreeSearchResult(int index);
    /**
     * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
     */
    int getTreeSearchResultCount();
    /**
     * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
     */
    java.util.List<? extends maximum.industries.Instance.TreeSearchResultOrBuilder> 
        getTreeSearchResultOrBuilderList();
    /**
     * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
     */
    maximum.industries.Instance.TreeSearchResultOrBuilder getTreeSearchResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code maximum.industries.TrainingInstance}
   */
  public  static final class TrainingInstance extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:maximum.industries.TrainingInstance)
      TrainingInstanceOrBuilder {
    // Use TrainingInstance.newBuilder() to construct.
    private TrainingInstance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrainingInstance() {
      boardState_ = com.google.protobuf.ByteString.EMPTY;
      player_ = 0;
      outcome_ = 0;
      gameLength_ = 0;
      treeSearchResult_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TrainingInstance(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              boardState_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              player_ = rawValue;
              break;
            }
            case 24: {

              outcome_ = input.readUInt32();
              break;
            }
            case 32: {

              gameLength_ = input.readUInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                treeSearchResult_ = new java.util.ArrayList<maximum.industries.Instance.TreeSearchResult>();
                mutable_bitField0_ |= 0x00000010;
              }
              treeSearchResult_.add(
                  input.readMessage(maximum.industries.Instance.TreeSearchResult.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          treeSearchResult_ = java.util.Collections.unmodifiableList(treeSearchResult_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return maximum.industries.Instance.internal_static_maximum_industries_TrainingInstance_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return maximum.industries.Instance.internal_static_maximum_industries_TrainingInstance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              maximum.industries.Instance.TrainingInstance.class, maximum.industries.Instance.TrainingInstance.Builder.class);
    }

    private int bitField0_;
    public static final int BOARD_STATE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString boardState_;
    /**
     * <code>bytes board_state = 1;</code>
     */
    public com.google.protobuf.ByteString getBoardState() {
      return boardState_;
    }

    public static final int PLAYER_FIELD_NUMBER = 2;
    private int player_;
    /**
     * <code>.maximum.industries.Player player = 2;</code>
     */
    public int getPlayerValue() {
      return player_;
    }
    /**
     * <code>.maximum.industries.Player player = 2;</code>
     */
    public maximum.industries.Instance.Player getPlayer() {
      maximum.industries.Instance.Player result = maximum.industries.Instance.Player.valueOf(player_);
      return result == null ? maximum.industries.Instance.Player.UNRECOGNIZED : result;
    }

    public static final int OUTCOME_FIELD_NUMBER = 3;
    private int outcome_;
    /**
     * <code>uint32 outcome = 3;</code>
     */
    public int getOutcome() {
      return outcome_;
    }

    public static final int GAME_LENGTH_FIELD_NUMBER = 4;
    private int gameLength_;
    /**
     * <code>uint32 game_length = 4;</code>
     */
    public int getGameLength() {
      return gameLength_;
    }

    public static final int TREE_SEARCH_RESULT_FIELD_NUMBER = 5;
    private java.util.List<maximum.industries.Instance.TreeSearchResult> treeSearchResult_;
    /**
     * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
     */
    public java.util.List<maximum.industries.Instance.TreeSearchResult> getTreeSearchResultList() {
      return treeSearchResult_;
    }
    /**
     * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
     */
    public java.util.List<? extends maximum.industries.Instance.TreeSearchResultOrBuilder> 
        getTreeSearchResultOrBuilderList() {
      return treeSearchResult_;
    }
    /**
     * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
     */
    public int getTreeSearchResultCount() {
      return treeSearchResult_.size();
    }
    /**
     * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
     */
    public maximum.industries.Instance.TreeSearchResult getTreeSearchResult(int index) {
      return treeSearchResult_.get(index);
    }
    /**
     * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
     */
    public maximum.industries.Instance.TreeSearchResultOrBuilder getTreeSearchResultOrBuilder(
        int index) {
      return treeSearchResult_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!boardState_.isEmpty()) {
        output.writeBytes(1, boardState_);
      }
      if (player_ != maximum.industries.Instance.Player.WHITE.getNumber()) {
        output.writeEnum(2, player_);
      }
      if (outcome_ != 0) {
        output.writeUInt32(3, outcome_);
      }
      if (gameLength_ != 0) {
        output.writeUInt32(4, gameLength_);
      }
      for (int i = 0; i < treeSearchResult_.size(); i++) {
        output.writeMessage(5, treeSearchResult_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!boardState_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, boardState_);
      }
      if (player_ != maximum.industries.Instance.Player.WHITE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, player_);
      }
      if (outcome_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, outcome_);
      }
      if (gameLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, gameLength_);
      }
      for (int i = 0; i < treeSearchResult_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, treeSearchResult_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof maximum.industries.Instance.TrainingInstance)) {
        return super.equals(obj);
      }
      maximum.industries.Instance.TrainingInstance other = (maximum.industries.Instance.TrainingInstance) obj;

      boolean result = true;
      result = result && getBoardState()
          .equals(other.getBoardState());
      result = result && player_ == other.player_;
      result = result && (getOutcome()
          == other.getOutcome());
      result = result && (getGameLength()
          == other.getGameLength());
      result = result && getTreeSearchResultList()
          .equals(other.getTreeSearchResultList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BOARD_STATE_FIELD_NUMBER;
      hash = (53 * hash) + getBoardState().hashCode();
      hash = (37 * hash) + PLAYER_FIELD_NUMBER;
      hash = (53 * hash) + player_;
      hash = (37 * hash) + OUTCOME_FIELD_NUMBER;
      hash = (53 * hash) + getOutcome();
      hash = (37 * hash) + GAME_LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getGameLength();
      if (getTreeSearchResultCount() > 0) {
        hash = (37 * hash) + TREE_SEARCH_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getTreeSearchResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static maximum.industries.Instance.TrainingInstance parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maximum.industries.Instance.TrainingInstance parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maximum.industries.Instance.TrainingInstance parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maximum.industries.Instance.TrainingInstance parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maximum.industries.Instance.TrainingInstance parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static maximum.industries.Instance.TrainingInstance parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static maximum.industries.Instance.TrainingInstance parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static maximum.industries.Instance.TrainingInstance parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static maximum.industries.Instance.TrainingInstance parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static maximum.industries.Instance.TrainingInstance parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static maximum.industries.Instance.TrainingInstance parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static maximum.industries.Instance.TrainingInstance parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(maximum.industries.Instance.TrainingInstance prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code maximum.industries.TrainingInstance}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:maximum.industries.TrainingInstance)
        maximum.industries.Instance.TrainingInstanceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return maximum.industries.Instance.internal_static_maximum_industries_TrainingInstance_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return maximum.industries.Instance.internal_static_maximum_industries_TrainingInstance_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                maximum.industries.Instance.TrainingInstance.class, maximum.industries.Instance.TrainingInstance.Builder.class);
      }

      // Construct using maximum.industries.Instance.TrainingInstance.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTreeSearchResultFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        boardState_ = com.google.protobuf.ByteString.EMPTY;

        player_ = 0;

        outcome_ = 0;

        gameLength_ = 0;

        if (treeSearchResultBuilder_ == null) {
          treeSearchResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          treeSearchResultBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return maximum.industries.Instance.internal_static_maximum_industries_TrainingInstance_descriptor;
      }

      public maximum.industries.Instance.TrainingInstance getDefaultInstanceForType() {
        return maximum.industries.Instance.TrainingInstance.getDefaultInstance();
      }

      public maximum.industries.Instance.TrainingInstance build() {
        maximum.industries.Instance.TrainingInstance result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public maximum.industries.Instance.TrainingInstance buildPartial() {
        maximum.industries.Instance.TrainingInstance result = new maximum.industries.Instance.TrainingInstance(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.boardState_ = boardState_;
        result.player_ = player_;
        result.outcome_ = outcome_;
        result.gameLength_ = gameLength_;
        if (treeSearchResultBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            treeSearchResult_ = java.util.Collections.unmodifiableList(treeSearchResult_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.treeSearchResult_ = treeSearchResult_;
        } else {
          result.treeSearchResult_ = treeSearchResultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof maximum.industries.Instance.TrainingInstance) {
          return mergeFrom((maximum.industries.Instance.TrainingInstance)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(maximum.industries.Instance.TrainingInstance other) {
        if (other == maximum.industries.Instance.TrainingInstance.getDefaultInstance()) return this;
        if (other.getBoardState() != com.google.protobuf.ByteString.EMPTY) {
          setBoardState(other.getBoardState());
        }
        if (other.player_ != 0) {
          setPlayerValue(other.getPlayerValue());
        }
        if (other.getOutcome() != 0) {
          setOutcome(other.getOutcome());
        }
        if (other.getGameLength() != 0) {
          setGameLength(other.getGameLength());
        }
        if (treeSearchResultBuilder_ == null) {
          if (!other.treeSearchResult_.isEmpty()) {
            if (treeSearchResult_.isEmpty()) {
              treeSearchResult_ = other.treeSearchResult_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureTreeSearchResultIsMutable();
              treeSearchResult_.addAll(other.treeSearchResult_);
            }
            onChanged();
          }
        } else {
          if (!other.treeSearchResult_.isEmpty()) {
            if (treeSearchResultBuilder_.isEmpty()) {
              treeSearchResultBuilder_.dispose();
              treeSearchResultBuilder_ = null;
              treeSearchResult_ = other.treeSearchResult_;
              bitField0_ = (bitField0_ & ~0x00000010);
              treeSearchResultBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTreeSearchResultFieldBuilder() : null;
            } else {
              treeSearchResultBuilder_.addAllMessages(other.treeSearchResult_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        maximum.industries.Instance.TrainingInstance parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (maximum.industries.Instance.TrainingInstance) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString boardState_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes board_state = 1;</code>
       */
      public com.google.protobuf.ByteString getBoardState() {
        return boardState_;
      }
      /**
       * <code>bytes board_state = 1;</code>
       */
      public Builder setBoardState(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        boardState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes board_state = 1;</code>
       */
      public Builder clearBoardState() {
        
        boardState_ = getDefaultInstance().getBoardState();
        onChanged();
        return this;
      }

      private int player_ = 0;
      /**
       * <code>.maximum.industries.Player player = 2;</code>
       */
      public int getPlayerValue() {
        return player_;
      }
      /**
       * <code>.maximum.industries.Player player = 2;</code>
       */
      public Builder setPlayerValue(int value) {
        player_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.maximum.industries.Player player = 2;</code>
       */
      public maximum.industries.Instance.Player getPlayer() {
        maximum.industries.Instance.Player result = maximum.industries.Instance.Player.valueOf(player_);
        return result == null ? maximum.industries.Instance.Player.UNRECOGNIZED : result;
      }
      /**
       * <code>.maximum.industries.Player player = 2;</code>
       */
      public Builder setPlayer(maximum.industries.Instance.Player value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        player_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.maximum.industries.Player player = 2;</code>
       */
      public Builder clearPlayer() {
        
        player_ = 0;
        onChanged();
        return this;
      }

      private int outcome_ ;
      /**
       * <code>uint32 outcome = 3;</code>
       */
      public int getOutcome() {
        return outcome_;
      }
      /**
       * <code>uint32 outcome = 3;</code>
       */
      public Builder setOutcome(int value) {
        
        outcome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 outcome = 3;</code>
       */
      public Builder clearOutcome() {
        
        outcome_ = 0;
        onChanged();
        return this;
      }

      private int gameLength_ ;
      /**
       * <code>uint32 game_length = 4;</code>
       */
      public int getGameLength() {
        return gameLength_;
      }
      /**
       * <code>uint32 game_length = 4;</code>
       */
      public Builder setGameLength(int value) {
        
        gameLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 game_length = 4;</code>
       */
      public Builder clearGameLength() {
        
        gameLength_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<maximum.industries.Instance.TreeSearchResult> treeSearchResult_ =
        java.util.Collections.emptyList();
      private void ensureTreeSearchResultIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          treeSearchResult_ = new java.util.ArrayList<maximum.industries.Instance.TreeSearchResult>(treeSearchResult_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          maximum.industries.Instance.TreeSearchResult, maximum.industries.Instance.TreeSearchResult.Builder, maximum.industries.Instance.TreeSearchResultOrBuilder> treeSearchResultBuilder_;

      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public java.util.List<maximum.industries.Instance.TreeSearchResult> getTreeSearchResultList() {
        if (treeSearchResultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(treeSearchResult_);
        } else {
          return treeSearchResultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public int getTreeSearchResultCount() {
        if (treeSearchResultBuilder_ == null) {
          return treeSearchResult_.size();
        } else {
          return treeSearchResultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public maximum.industries.Instance.TreeSearchResult getTreeSearchResult(int index) {
        if (treeSearchResultBuilder_ == null) {
          return treeSearchResult_.get(index);
        } else {
          return treeSearchResultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public Builder setTreeSearchResult(
          int index, maximum.industries.Instance.TreeSearchResult value) {
        if (treeSearchResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTreeSearchResultIsMutable();
          treeSearchResult_.set(index, value);
          onChanged();
        } else {
          treeSearchResultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public Builder setTreeSearchResult(
          int index, maximum.industries.Instance.TreeSearchResult.Builder builderForValue) {
        if (treeSearchResultBuilder_ == null) {
          ensureTreeSearchResultIsMutable();
          treeSearchResult_.set(index, builderForValue.build());
          onChanged();
        } else {
          treeSearchResultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public Builder addTreeSearchResult(maximum.industries.Instance.TreeSearchResult value) {
        if (treeSearchResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTreeSearchResultIsMutable();
          treeSearchResult_.add(value);
          onChanged();
        } else {
          treeSearchResultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public Builder addTreeSearchResult(
          int index, maximum.industries.Instance.TreeSearchResult value) {
        if (treeSearchResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTreeSearchResultIsMutable();
          treeSearchResult_.add(index, value);
          onChanged();
        } else {
          treeSearchResultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public Builder addTreeSearchResult(
          maximum.industries.Instance.TreeSearchResult.Builder builderForValue) {
        if (treeSearchResultBuilder_ == null) {
          ensureTreeSearchResultIsMutable();
          treeSearchResult_.add(builderForValue.build());
          onChanged();
        } else {
          treeSearchResultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public Builder addTreeSearchResult(
          int index, maximum.industries.Instance.TreeSearchResult.Builder builderForValue) {
        if (treeSearchResultBuilder_ == null) {
          ensureTreeSearchResultIsMutable();
          treeSearchResult_.add(index, builderForValue.build());
          onChanged();
        } else {
          treeSearchResultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public Builder addAllTreeSearchResult(
          java.lang.Iterable<? extends maximum.industries.Instance.TreeSearchResult> values) {
        if (treeSearchResultBuilder_ == null) {
          ensureTreeSearchResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, treeSearchResult_);
          onChanged();
        } else {
          treeSearchResultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public Builder clearTreeSearchResult() {
        if (treeSearchResultBuilder_ == null) {
          treeSearchResult_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          treeSearchResultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public Builder removeTreeSearchResult(int index) {
        if (treeSearchResultBuilder_ == null) {
          ensureTreeSearchResultIsMutable();
          treeSearchResult_.remove(index);
          onChanged();
        } else {
          treeSearchResultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public maximum.industries.Instance.TreeSearchResult.Builder getTreeSearchResultBuilder(
          int index) {
        return getTreeSearchResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public maximum.industries.Instance.TreeSearchResultOrBuilder getTreeSearchResultOrBuilder(
          int index) {
        if (treeSearchResultBuilder_ == null) {
          return treeSearchResult_.get(index);  } else {
          return treeSearchResultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public java.util.List<? extends maximum.industries.Instance.TreeSearchResultOrBuilder> 
           getTreeSearchResultOrBuilderList() {
        if (treeSearchResultBuilder_ != null) {
          return treeSearchResultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(treeSearchResult_);
        }
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public maximum.industries.Instance.TreeSearchResult.Builder addTreeSearchResultBuilder() {
        return getTreeSearchResultFieldBuilder().addBuilder(
            maximum.industries.Instance.TreeSearchResult.getDefaultInstance());
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public maximum.industries.Instance.TreeSearchResult.Builder addTreeSearchResultBuilder(
          int index) {
        return getTreeSearchResultFieldBuilder().addBuilder(
            index, maximum.industries.Instance.TreeSearchResult.getDefaultInstance());
      }
      /**
       * <code>repeated .maximum.industries.TreeSearchResult tree_search_result = 5;</code>
       */
      public java.util.List<maximum.industries.Instance.TreeSearchResult.Builder> 
           getTreeSearchResultBuilderList() {
        return getTreeSearchResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          maximum.industries.Instance.TreeSearchResult, maximum.industries.Instance.TreeSearchResult.Builder, maximum.industries.Instance.TreeSearchResultOrBuilder> 
          getTreeSearchResultFieldBuilder() {
        if (treeSearchResultBuilder_ == null) {
          treeSearchResultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              maximum.industries.Instance.TreeSearchResult, maximum.industries.Instance.TreeSearchResult.Builder, maximum.industries.Instance.TreeSearchResultOrBuilder>(
                  treeSearchResult_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          treeSearchResult_ = null;
        }
        return treeSearchResultBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:maximum.industries.TrainingInstance)
    }

    // @@protoc_insertion_point(class_scope:maximum.industries.TrainingInstance)
    private static final maximum.industries.Instance.TrainingInstance DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new maximum.industries.Instance.TrainingInstance();
    }

    public static maximum.industries.Instance.TrainingInstance getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TrainingInstance>
        PARSER = new com.google.protobuf.AbstractParser<TrainingInstance>() {
      public TrainingInstance parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TrainingInstance(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrainingInstance> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrainingInstance> getParserForType() {
      return PARSER;
    }

    public maximum.industries.Instance.TrainingInstance getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maximum_industries_WinLoseDraw_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maximum_industries_WinLoseDraw_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maximum_industries_TreeSearchResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maximum_industries_TreeSearchResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maximum_industries_TrainingInstance_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maximum_industries_TrainingInstance_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0src/main/proto/maximum/industries/inst" +
      "ance.proto\022\022maximum.industries\"6\n\013WinLos" +
      "eDraw\022\013\n\003win\030\001 \001(\002\022\014\n\004lose\030\002 \001(\002\022\014\n\004draw" +
      "\030\003 \001(\002\"\210\001\n\020TreeSearchResult\022\r\n\005index\030\001 \001" +
      "(\r\022)\n\004type\030\002 \001(\0162\033.maximum.industries.Ts" +
      "rType\022\014\n\004prob\030\003 \001(\002\022,\n\003wld\030\004 \001(\0132\037.maxim" +
      "um.industries.WinLoseDraw\"\273\001\n\020TrainingIn" +
      "stance\022\023\n\013board_state\030\001 \001(\014\022*\n\006player\030\002 " +
      "\001(\0162\032.maximum.industries.Player\022\017\n\007outco" +
      "me\030\003 \001(\r\022\023\n\013game_length\030\004 \001(\r\022@\n\022tree_se",
      "arch_result\030\005 \003(\0132$.maximum.industries.T" +
      "reeSearchResult*\036\n\006Player\022\t\n\005WHITE\020\000\022\t\n\005" +
      "BLACK\020\001**\n\007TsrType\022\r\n\tMOVE_PROB\020\000\022\020\n\014OUT" +
      "COME_PROB\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_maximum_industries_WinLoseDraw_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maximum_industries_WinLoseDraw_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maximum_industries_WinLoseDraw_descriptor,
        new java.lang.String[] { "Win", "Lose", "Draw", });
    internal_static_maximum_industries_TreeSearchResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_maximum_industries_TreeSearchResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maximum_industries_TreeSearchResult_descriptor,
        new java.lang.String[] { "Index", "Type", "Prob", "Wld", });
    internal_static_maximum_industries_TrainingInstance_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_maximum_industries_TrainingInstance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maximum_industries_TrainingInstance_descriptor,
        new java.lang.String[] { "BoardState", "Player", "Outcome", "GameLength", "TreeSearchResult", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
