# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maximum/industries/instance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='maximum/industries/instance.proto',
  package='maximum.industries',
  syntax='proto3',
  serialized_pb=_b('\n!maximum/industries/instance.proto\x12\x12maximum.industries\"6\n\x0bWinLoseDraw\x12\x0b\n\x03win\x18\x01 \x01(\x02\x12\x0c\n\x04lose\x18\x02 \x01(\x02\x12\x0c\n\x04\x64raw\x18\x03 \x01(\x02\"\x88\x01\n\x10TreeSearchResult\x12\r\n\x05index\x18\x01 \x01(\r\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.maximum.industries.TsrType\x12\x0c\n\x04prob\x18\x03 \x01(\x02\x12,\n\x03wld\x18\x04 \x01(\x0b\x32\x1f.maximum.industries.WinLoseDraw\"\xbb\x01\n\x10TrainingInstance\x12\x13\n\x0b\x62oard_state\x18\x01 \x01(\x0c\x12*\n\x06player\x18\x02 \x01(\x0e\x32\x1a.maximum.industries.Player\x12\x0f\n\x07outcome\x18\x03 \x01(\x05\x12\x13\n\x0bgame_length\x18\x04 \x01(\r\x12@\n\x12tree_search_result\x18\x05 \x03(\x0b\x32$.maximum.industries.TreeSearchResult*\x1e\n\x06Player\x12\t\n\x05WHITE\x10\x00\x12\t\n\x05\x42LACK\x10\x01**\n\x07TsrType\x12\r\n\tMOVE_PROB\x10\x00\x12\x10\n\x0cOUTCOME_PROB\x10\x01\x62\x06proto3')
)

_PLAYER = _descriptor.EnumDescriptor(
  name='Player',
  full_name='maximum.industries.Player',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WHITE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLACK', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=442,
  serialized_end=472,
)
_sym_db.RegisterEnumDescriptor(_PLAYER)

Player = enum_type_wrapper.EnumTypeWrapper(_PLAYER)
_TSRTYPE = _descriptor.EnumDescriptor(
  name='TsrType',
  full_name='maximum.industries.TsrType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MOVE_PROB', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTCOME_PROB', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=474,
  serialized_end=516,
)
_sym_db.RegisterEnumDescriptor(_TSRTYPE)

TsrType = enum_type_wrapper.EnumTypeWrapper(_TSRTYPE)
WHITE = 0
BLACK = 1
MOVE_PROB = 0
OUTCOME_PROB = 1



_WINLOSEDRAW = _descriptor.Descriptor(
  name='WinLoseDraw',
  full_name='maximum.industries.WinLoseDraw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='win', full_name='maximum.industries.WinLoseDraw.win', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lose', full_name='maximum.industries.WinLoseDraw.lose', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='draw', full_name='maximum.industries.WinLoseDraw.draw', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=111,
)


_TREESEARCHRESULT = _descriptor.Descriptor(
  name='TreeSearchResult',
  full_name='maximum.industries.TreeSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='maximum.industries.TreeSearchResult.index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='maximum.industries.TreeSearchResult.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prob', full_name='maximum.industries.TreeSearchResult.prob', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wld', full_name='maximum.industries.TreeSearchResult.wld', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=250,
)


_TRAININGINSTANCE = _descriptor.Descriptor(
  name='TrainingInstance',
  full_name='maximum.industries.TrainingInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='board_state', full_name='maximum.industries.TrainingInstance.board_state', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='maximum.industries.TrainingInstance.player', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outcome', full_name='maximum.industries.TrainingInstance.outcome', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game_length', full_name='maximum.industries.TrainingInstance.game_length', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tree_search_result', full_name='maximum.industries.TrainingInstance.tree_search_result', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=440,
)

_TREESEARCHRESULT.fields_by_name['type'].enum_type = _TSRTYPE
_TREESEARCHRESULT.fields_by_name['wld'].message_type = _WINLOSEDRAW
_TRAININGINSTANCE.fields_by_name['player'].enum_type = _PLAYER
_TRAININGINSTANCE.fields_by_name['tree_search_result'].message_type = _TREESEARCHRESULT
DESCRIPTOR.message_types_by_name['WinLoseDraw'] = _WINLOSEDRAW
DESCRIPTOR.message_types_by_name['TreeSearchResult'] = _TREESEARCHRESULT
DESCRIPTOR.message_types_by_name['TrainingInstance'] = _TRAININGINSTANCE
DESCRIPTOR.enum_types_by_name['Player'] = _PLAYER
DESCRIPTOR.enum_types_by_name['TsrType'] = _TSRTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WinLoseDraw = _reflection.GeneratedProtocolMessageType('WinLoseDraw', (_message.Message,), dict(
  DESCRIPTOR = _WINLOSEDRAW,
  __module__ = 'maximum.industries.instance_pb2'
  # @@protoc_insertion_point(class_scope:maximum.industries.WinLoseDraw)
  ))
_sym_db.RegisterMessage(WinLoseDraw)

TreeSearchResult = _reflection.GeneratedProtocolMessageType('TreeSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _TREESEARCHRESULT,
  __module__ = 'maximum.industries.instance_pb2'
  # @@protoc_insertion_point(class_scope:maximum.industries.TreeSearchResult)
  ))
_sym_db.RegisterMessage(TreeSearchResult)

TrainingInstance = _reflection.GeneratedProtocolMessageType('TrainingInstance', (_message.Message,), dict(
  DESCRIPTOR = _TRAININGINSTANCE,
  __module__ = 'maximum.industries.instance_pb2'
  # @@protoc_insertion_point(class_scope:maximum.industries.TrainingInstance)
  ))
_sym_db.RegisterMessage(TrainingInstance)


# @@protoc_insertion_point(module_scope)
